/* Copyright (c) 2023 Gordon Williams. See the file LICENSE for copying permission. */
/*

8x8 VGA-style fixed-width font

Usage:

```
require("FontVGA8").add(Graphics);
g.setFont("VGA8");
g.drawString("0123456789");
```
*/
exports.add = function(graphics) {
  graphics.prototype.setFontVGA8 = function() {
    return this.setFontCustom(atob("AAAAAAAAAAB+gamNjamBfn7/1/Pz1/9+cPj8fvz4cAAQOHz+fDgQABxc+f/5XBwAGDx9/308GAAAABg8PBgAAP//58PD5///ADxmQkJmPAD/w5m9vZnD/w4fERG//uDwAHL6j4/6cgADB//+oKDg4AP//qCgpv78Wlo85+c8Wlr+fHw4OBAQABAQODh8fP4AACRm//9mJAAA+voAAPr6AGDwkP7+gP7+Aln9paW/mkAADg4ODg4OAAEpbf//bSkBACBg/v5gIAAACAz+/gwIABAQEFR8OBAAEDh8VBAQEAA8PAQEBAQEABA4fBAQfDgQDBw8fHw8HAxgcHh8fHhwYAAAAAAAAAAAAABg+vpgAAAAwOAAAODAACj+/ij+/igAACR01tZcSABiZgwYMGZGAAxe8rrsXhIAAAAg4MAAAAAAADh8xoIAAAAAgsZ8OAAAEFR8ODh8VBAAEBB8fBAQAAAAAQcGAAAAABAQEBAQEAAAAAAGBgAAAAYMGDBgwIAAOHzGksZ8OAAAAkL+/gICAELGjpqS9mYARMaSkpL+bAAYOGjK/v4KAPT2kpKSnowAPH7SkpIeDADAwI6esODAAGz+kpKS/mwAYPKSkpb8eAAAAABmZgAAAAAAAWdmAAAAAAAQOGzGggAAJCQkJCQkAACCxmw4EAAAQMCAmrrgQAB8/oK6uvh4AD5+0JDQfj4Agv7+kpL+bAA4fMaCgsZEAIL+/oLGfDgAgv7+krqCxgCC/v6SuIDAADh8xoKKzE4A/v4QEBD+/gAAAIL+/oIAAAwOAoL+/IAAgv7+EDjuxgCC/v6CAgYOAP7+cDhw/v4A/v5gMBj+/gB8/oKCgv58AIL+/pKQ8GAAfP6Cgof/fQCC/v6QmP5mAABE5rKazkQAAODC/v7C4AD8/gICAv78APj8BgIG/PgA/P4GHAb+/ADG7jgQOO7GAADg8h4e8uAA4saOmrLmzgAAAP7+goIAAIDAYDAYDAYAAACCgv7+AAAQMGDAYDAQAAEBAQEBAQEBAACAwGAgAAAELioqPB4CAIL+/CIiPhwAHD4iIiI2FAAcPiKi/P4CABw+KioqOhgAEn7+kpDAQAAZPSUlHz4gAIL+/hAgPh4AAAAivr4CAAAABgcBAb++AIL+/ggcNiIAAACC/v4CAAA+PjAeMD4eACA+HiAgPh4AHD4iIiI+HAAhPx8lJDwYABg8JCUfPyEAIj4eMiAwEAASOioqKi4kACAg/P4iJgQAPD4CAjw+AgA4PAYCBjw4ADw+BhwGPjwAIjYcCBw2IgA5PQUFBT8+AAAyJi46MiYAABAQfO6CggAAAAD+/gAAAACCgu58EBAAQMCAwEDAgAAOHjJiMh4OAHj9hYWHzkgAvL4CAry+AgAcPipq6roYAESuqqq8nkIAhK4qKjyeggAELqrqfB4CAAQu6uo8HgIAGDwlJScmJABcvqqqqrpYAJy+KioqupgAHD6q6mo6GAAAgKI+PoKAAECAor6+gkAAAACS3l4CAACevmhIaL6eAB5+6Kjofh4APj5q6qoiIgAELio+PioqAD5+0JD+/pIAXL6ioqK+XACcviIiIr6cABw+ouJiPhwAXJ6CgpxeAgA8vsJCPD4CALm9BQUFv74AmLxmQma8mAC8vgICAr68ABg8JOfnJCQAEn7+ksJmBAAA1PQ/P/TUAP//kJD0bx8FBAYSfvyQwEAELmrqvB4CAAAAEl7eggAAHD4iYuK+HAA8PkLCvD4CAFDejtBQ3o4AXt6YzEbengAAZPSU9PQUAABk9JT0ZAAAAAQOurICBgQcHBAQEBAQABAQEBAQHBwAQvb8GDN33YlC9vwaNmvfggAADL6+DAAAEDhsRBA4bEREbDgQRGw4EFUAqgBVAKoAVapVqlWqVapV/6r/Vf+q/wAAAP//AAAACAgI//8AAAAoKCj//wAAAAgI//8A//8ACAgPDwgPDwAoKCg/PwAAACgo7+8A//8AAAD//wD//wAoKC8vID8/ACgo6OgI+PgACAj4+Aj4+AAoKCj4+AAAAAgICA8PAAAAAAAA+PgICAgICAj4+AgICAgICA8PCAgIAAAA//8ICAgICAgICAgICAgICP//CAgIAAAA//8oKCgAAP//AP//CAAA+PgI6OgoAAA/PyAvLygoKOjoCOjoKCgoLy8gLy8oAAD//wDv7ygoKCgoKCgoKCgo7+8A7+8oKCgo6OgoKCgICPj4CPj4CCgoKC8vKCgoCAgPDwgPDwgAAPj4CPj4CAAAAPj4KCgoAAAAPz8oKCgAAA8PCA8PCAgI//8I//8IKCgo//8oKCgICAj4+AAAAAAAAA8PCAgI//////////8PDw8PDw8PD/////8AAAAAAAAAAP/////w8PDw8PDw8Bw+IjYcNiIAfv6AkPpuBAD+/oCAgMDAACA+PiA+PiAAxu66koLGxgAcPiI+PCAgAAE/PgICPjwAIGBAfj5gQAAAmb3n572ZADh81pLWfDgAMn7OgM5+MgAADB5S8r6cABg8JDw8JDwYGT8mPHzkvBgAOHzWkpKSAD5+QEBAfj4AVFRUVFRUVAAAIiL6+iIiAAACitpyIgIAAAIictqKAgAAAAB//4DgYAYHAf/+AAAAABAQVFQQEAAkbEhsJGxIAABg8JDwYAAAAAAAGBgAAAAAAAAQEAAAAAgMDgP//4CAAID4eID4eAAAiJi46EgAAAAAPDw8PAAAAAAAAAAAAAA="), 0, 8, 8);
  }
}
