/* Copyright (c) 2015 Dennis Bemmann. See the file LICENSE for copying permission. */
/*
FontDennis8.js
==============

from FontDennis8.png

Usage:

```
require("FontDennis8").add(Graphics);
g.setFontDennis8();
g.drawString("\x90 \x91\x92\x93\x94\x95\x96\x97 Dennis8 \x9f \x8c \x8d \x89",0,0);
g.drawString("ça ¿sí? \xbc\xa3 \xbd\xb5\xa6 \x82\x83\x84\x85 \xac\xad\x86",0,12);
g.drawString("\xa0 Bäh böse Ärzte in Küche\xaf",0,24);
```
*/
var font = atob("AAAAAPoAwADAAFhw2HDQAGSS/5JMAGCW+DzSDAxSolIMEsAAPEKBAIFCPABIMOAwSAAQEHwQEAABBgAQEBAQAAIAAwwwwAB8ipKifABA/gBChoqSYgCEkrLSjAAYKEj+CADkoqKinAA8UpKSDACAgI6wwABskpKSbABgkpKUeAAiAAEmABAoRAAoKCgoKABEKBAAQIqQYAA8WqW9RDgOOMg4DgD+kpKSbAB8goKCRAD+goJEOAD+kpKCAP6QkIAAfIKCklwA/hAQEP4A/gAMAgIC/AD+EChEggD+AgICAP5AIED+AP7AMAz+AHyCgoJ8AP6QkJBgAHyChoN8AP6QmJRiAGSSkpJMAICA/oCAAPwCAgL8AOAYBhjgAPAOMA7wAMYoECjGAMAgHiDAAI6SosIA/4EAwDAMAwCB/wBAgEAAAQEBAQEBEn6SggQABCoqHgD+IiIcABwiIhQAHCIi/gAcKioYACB+oIAAGCUlPgD+ICAeAL4AAQG+AP4IFCIA/AIAPiAeIB4APiAgHgAcIiIcAD8kJBgAGCQkPwA+ECAgABIqKiQAIPwiADwCAjwAIBgGGCAAOAYIBjgAIhQIFCIAIRkGGCAAJioyIgAQboEA5wCBbhAAQIDAQIAAPFqlpUI8cPh8+HAAcDhwACBg/mAgAAgM/gwIABA4fBAQABAQfDgQAHxERER8AHxE9CRcAHxUbFR8AP58OBAAEDh8/gACAAIAAgB8fHx8fAD+/gD+/gACilIiAgACIlKKAgA+Yu5iPgACAgICAgAGBgYGBgAODg4ODgAeHh4eHgA+Pj4+PgB+fn5+fgD+/v7+/gD+/v7+/gAAAAAA/gD+/gD+/v4A/v7+/gD+/v7+/gA4OHz+/gAMDPBAIACeADhE/kQIABJ8koIEAEQ4KDhEAKhoPmioACh8qqqCAARSqpRAAJCkqKSQAP6CupL+ABKqqqp6ABAoVChEADh8fHw4ADhUbFQ4AP6Cpor+ABAYHBgQAGCQkGAAIiL6IiIASJioSACIqKhQACBAgAB/BAQIfABgkP6A/gAwMAAAAAAASPgIADlFRUU5AEQoVCgQAOgWKl+CAOgQKVONAKj4BgofAAYJUQIADpRkFA4ADhRklA4ADlSUVA4ATpSUVI4AjjjIOI4ADlS0VA4APkj+kpIAeISFh0gAPqpqKiIAPmqqKiIAPmqqaiIAPqoqqiIAon4iACJ+ogBivmIAYj5iABB+UkI8AH6QiES+AByiYiIcABwiYqIcAAxSklIMAEySklKMALxCQkK8ACIUCBQiAD5DXWE+ADyCQgI8ADwCQoI8ABxCgkIcALwCAgK8ACAQTpAgAIH/JSQYAH+SkmwABKpqHgAEKmqeAARqql4ARKqqXoCEKiqeAARqql4ATFI8UjQAGCUnJAgAHKpqKhgAHCpqmAAcaqpYAByqKpgAon4CACJ+ggBivkIAYj5CAKRKqhoMAF6QkE6AAAySUgwADBJSjAAMUpJMAEySUowAnCIinAAQEFQQEAA6TFRkuAAcgkIcABxCghwAHEKCXABcAgJcADAKSoo8AIH/FQgAMIoKijwA");
var widths = atob("BAIEBgYGBgIEBAYGAwUCBQYDBgYGBgYGBgYCAwQGBAUGBgYGBgUFBgYCBgYFBgYGBgYGBgYGBgYGBgUDBQMEBgYFBQUFBQUFBQIEBQMGBQUFBQUFBAUGBgYGBQQCBAYGBgQGBgYGBgYGBQUGBgYGBgYGBgYGBgYGBgQCAwQFBgYGAgYGBgYGBgYGBgYGBgYGBQYFBQQGBgMEBAYGBgYGBQYGBgYGBgYGBgYGBgQEBAQGBgYGBgYGBgYGBgYGBgYFBQUFBQUFBgYGBQUFBAQEBAYGBQUFBQUGBgUFBQUGBQY=");

exports.add = function(graphics) {
  graphics.prototype.setFontDennis8 = function() {
    this.setFontCustom(font, 32, widths, 8);
  }
}
