/* Copyright (c) 2014 Spence Konde. See the file LICENSE for copying permission. */
/* 

Created from http://uzebox.org/wiki/images/5/50/Dangen_charset_6x12.png with http://ebfc.mattbrailsford.com/

Usage:

```
require("Font6x12").add(Graphics);
g.setFont6x12();
g.drawString("0123456789");
```
*/
var font = atob("AAAAAAAAfkAAwAAAwAAAEQf8EQf8EQAAGIJEf+JEE4AAMMMQBgCMMMAAM4TEMkB8AEwAgAAAHwIIQEAAQEIIHwAAFQDgBADgFQBABAHwBABAACAMAABABABABAAAAEAAAcBgGAYAAAP4RESEP4EEIEf8AEMMQUQkPEIIREREO4DwEQIQf8eISESER4P4SESEB4YAQcTgcAO4REREO4PEQkQoPwCIAAACCMAABACgEQIIAACQCQCQCQIIEQCgBAAAMAQ0RAOAP4TkUUP0P8RARAP8f8REREO4P4QEQEIIf8QEIIHwf8REREQEf8RARAQAP4QEREJ4f8BABAf8QEf8QEAYAEQEf4f8CgEQYMf8AEAEAEf8MADAMAf8f8GABgf8P4QEQEP4f8RARAOAP4QEQEP6f8RQRIOEOIREREI4QAQAf8QAQAAAf4AEAEf4eABwAMBweAf8AYBgAYf8YMGwBAGwYMYAGAB8GAYAQcRkWEYEf8QEAAYAGABgAcQEf8AAIAQAgAQAIAACACACACgAwAAAAYCkCkB8f8CECEB4B4CECEBIB4CECEf8B4CUCUBwCAP8SAQAB4CFCFD+f8CACAB8CET8AEACABT+AAf8BQCIAEQEf8AED8CAD8CAB8D8CACAB8B4CECEB4D/CECEB4B4CECED/D8BACAAABICkCkAYCAP4CECED4AEAED8DAAwAMAwDAD4AEA4AED4CMBQAgBQCMD4AFAFD+CMCUCkDEBAO4QEQEf8AAQEQEO4BAYAwAYAwA");
var widths = atob("BAIEBgYGBQMEBAUFAwUCBQQEBAQEBAQEBAQCAwUEBQQEBAQEBAQEBAQDBAQEBQQEBAQEBAQGBQUFBQQDBAMFBAMEBAQEBAQEBAMEBAMFBAQEBAQEBAQFBQUEBAQCBAQ=");
exports.add = function(graphics) {
  graphics.prototype.setFont6x12 = function() {
    this.setFontCustom(font, 32, widths, 12);
  }
}


