/* Copyright (c) 2014 Spence Konde. See the file LICENSE for copying permission. */
/* 

Created from http://uzebox.org/wiki/index.php?title=File:F8x16all.gif with http://ebfc.mattbrailsford.com/

Usage:

```
require("Font8x16").add(Graphics);
g.setFont8x16();
g.drawString("0123456789");
```
*/
var font = atob("AAAAAAAAAAAAABwAP7A/sBwAAABwAHgAAAAAAHgAcAAAAARAH/Af8ARAH/Af8ARAAAAcYD4wIhDiHOIcM/AZ4AAADDAMYADAAYADAAYwDDAAAAHgG/A+ECcQPeAb8AIQAAAIAHgAcAAAAA/AH+AwMCAQAAAgEDAwH+APwAAAAQAFQAfAA4ADgAfABUABAAEAAQAHwAfAAQABAAAAAAgAeABwAAABAAEAAQABAAEAAQABAAAAADAAMAAAADAAYADAAYADAAYADAAAAA/AH+AwMCAQMDAf4A/AAAAIEBgQP/A/8AAQABAAABBwMPAhkCMQJhA8MBgwAAAQIDAwIhAiECIQP/Ad4AAAAwAHAA0AGRA/8D/wARAAAD4gPjAiECIQIhAj8CHgAAAP4B/wMhAiECIQA/AB4AAAMAAwACDwIfAjAD4APAAAAB3gP/AiECIQIhA/8B3gAAAcAD4QIhAiECIwP+AfwAAADGAMYAAAABAMcAxgAAABAAOABsAMYBgwEBAAAASABIAEgASABIAEgAAAEBAYMAxgBsADgAEAAAAYADgAIAAjsCewPAAYAAAAD+Af8BAQE9AT0B/QD4AAAAfwD/AZADEAGQAP8AfwAAAgED/wP/AiECIQP/Ad4AAAD8Af4DAwIBAgEDAwGGAAACAQP/A/8CAQMDAf4A/AAAAgED/wP/AiECcQMDA4cAAAIBA/8D/wIhAnADAAOAAAAA/AH+AwMCEQIRAx4BnwAAA/8D/wAgACAAIAP/A/8AAAIBA/8D/wIBAAAADgAPAAECAQP/A/4CAAAAAgED/wP/ADAAeAPPA4cAAAIBA/8D/wIBAAEAAwAHAAAD/wP/AcAA4AHAA/8D/wAAA/8D/wHAAOAAcAP/A/8AAAH+A/8CAQIBAgED/wH+AAACAQP/A/8CIQIgA+ABwAAAAf4D/wIBAgcCA8P/wf5AAAIBA/8D/wIgAjAD/wHPAAABhgPHAmECIQIxA58BjgAAA4ADAQP/A/8DAQOAAAAD/gP/AAEAAQABA/8D/gAAA/gD/AAGAAMABgP8A/gAAAP+A/8ABwA8AAcD/wP+AAADAwPPAPwAeAD8A88DAwAAA8AD4QA/AD8D4QPAAAADhwMPAhkCMQJhA8MDhwAAA/8D/wIBAgEAAAHAAOAAcAA4ABwADgAHAAACAQIBA/8D/wAAAQADAAYADAAGAAMAAQAAAAAAQABAAEAAQABAAEAAQABEAAYAAwABAAAAAA4AXwBRAFEAfgA/AAEAAAIAA/8D/wBBAGEAPwAeAAAAPgB/AEEAQQBBAGMAIgAAAB4APwBhAkED/gP/AAEAAAA+AH8AUQBRAFEAcwAyAAAAIQH/A/8CIQMAAYAAAAA+QH9gQSBBID/gf8BAAAACAQP/A/8AIABAAH8APwAAAEEDfwN/AAEAAAAAwADgACBAI3/jf8AAAgED/wP/ABgAPABnAEMAAAIBA/8D/wABAAAAfwB/AGAAPgBgAH8APwAAAEAAfwA/AEAAQAB/AD8AAAA+AH8AQQBBAEEAfwA+AAAAQCB/4D/gQSBBAH8APgAAAD4AfwBBAEEgP+B/4EAgAABBAH8APwBhAEAAcAAwAAAAIgBzAFkASQBNAGcAIgAAAEAAQAH+A/8AQQBDAAIAAAB+AH8AAQABAH4AfwABAAAAfAB+AAMAAQADAH4AfAAAAH4AfwADAB4AAwB/AH4AAABBAGMAPgAcAD4AYwBBAAAAfiB/IAEgASABYH/Af4AAAGMAZwBNAFkAcQBjAEMAAAAgACAB/gPfAgECAQAAA/8D/wAAAgECAQPfAf4AIAAgAAAA==");
var widths = atob("BQUHCAgICAQFBQgHBAgDCAgHCAgICAgICAgDBAcHBwgICAgICAgICAgFCAgICAgICAgICAcICAgIBwgFCAUICAUICAgICAcICAUHCAUICAgICAgICAgICAgICAcDBw==");

exports.add = function(graphics) {
  graphics.prototype.setFont8x16 = function() {
    this.setFontCustom(font, 32, widths, 16);
  }
}

